apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dokarkivpleie
  namespace: teamdokumenthandtering
spec:
  env:
    - name: JDK_JAVA_OPTIONS
      value: "-XX:MaxRAMPercentage=75"
  envFrom:
    - secret: dokarkivpleie
  image: {{image}}
  port: 8080
  replicas:
    min: 1
    max: 1
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      memory: 512Mi
  liveness:
    path: /actuator/health/liveness
    initialDelay: 20
    failureThreshold: 10
  readiness:
    path: /actuator/health/readiness
    initialDelay: 20
    timeout: 3
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki